/* Samvid scene: the humanoid, shield spring, warm burst, orbit nodes, particles, and grid form the Samvid identity field. */
import { Canvas, useFrame } from "@react-three/fiber";
import { ContactShadows, Environment, Html, Lightformer } from "@react-three/drei";
import { Suspense, useMemo, useRef, useState } from "react";
import * as THREE from "three";
import { Robot } from "./robot-hero";

const NODES = [
  { label: "DID", sub: "decentralized identifier" }, { label: "NFT", sub: "asset ownership" }, { label: "RBAC", sub: "role permissions" },
  { label: "CONTRACT", sub: "on-chain rules" }, { label: "LEDGER", sub: "audit trail" }, { label: "PROOF", sub: "cryptographic auth" },
];
const HOLO = "#2b756c"; const HOLO_WARM = "#b56d3c"; const CORE = new THREE.Vector3(0, 0, 0); const RING_R = 2.05; const RING_TILT = 0.32;

function AttributeField({ open }: { open: boolean }) {
  const group = useRef<THREE.Group>(null);
  useFrame((state, raw) => { const dt = Math.min(raw, 0.05); if (!group.current) return; group.current.rotation.y -= dt * 0.16; const target = open ? 1 : 0.55; const s = group.current.scale.x; group.current.scale.setScalar(s + (target - s) * (1 - Math.exp(-5 * dt))); group.current.children.forEach((c, i) => { c.position.y = Math.sin(state.clock.elapsedTime * 0.8 + i * 1.1) * 0.09; }); });
  return <group ref={group} position={[0, 0.95, 0]} rotation={[RING_TILT, 0, 0]}>{NODES.map((node, i) => { const a = (i / NODES.length) * Math.PI * 2; const p = new THREE.Vector3(Math.cos(a) * RING_R, 0, Math.sin(a) * RING_R); const dir = CORE.clone().sub(p); const len = dir.length() - 0.95; const quat = new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0, 1, 0), dir.clone().normalize()); return <group key={node.label} position={p}><group quaternion={quat}><mesh position={[0, len / 2, 0]}><cylinderGeometry args={[0.004, 0.004, len, 6]} /><meshBasicMaterial color={HOLO} transparent opacity={open ? 0.45 : 0.14} depthWrite={false} /></mesh></group><mesh><icosahedronGeometry args={[0.11, 0]} /><meshStandardMaterial color={i % 3 === 0 ? HOLO_WARM : HOLO} emissive={i % 3 === 0 ? HOLO_WARM : HOLO} emissiveIntensity={2.4} roughness={0.2} /></mesh><mesh rotation={[-Math.PI / 2 - RING_TILT, 0, 0]}><ringGeometry args={[0.19, 0.21, 32]} /><meshBasicMaterial color={HOLO} transparent opacity={open ? 0.55 : 0.2} side={THREE.DoubleSide} /></mesh>{open && <Html center distanceFactor={9} position={[0, 0.34, 0]}><div className="node-chip"><span>{node.label}</span><em>{node.sub}</em></div></Html>}</group>; })}</group>;
}

function ChainRings({ open }: { open: boolean }) { const a = useRef<THREE.Mesh>(null); const b = useRef<THREE.Mesh>(null); useFrame((_, raw) => { const dt = Math.min(raw, 0.05); if (a.current) a.current.rotation.z += dt * 0.18; if (b.current) b.current.rotation.z -= dt * 0.26; }); return <group position={[0, 0.95, 0]} rotation={[RING_TILT, 0, 0]}><mesh ref={a} rotation={[-Math.PI / 2, 0, 0]}><torusGeometry args={[RING_R, 0.006, 6, 160]} /><meshBasicMaterial color={HOLO} transparent opacity={open ? 0.55 : 0.22} /></mesh><mesh ref={b} rotation={[-Math.PI / 2, 0, 0]}><torusGeometry args={[RING_R * 0.62, 0.005, 6, 128]} /><meshBasicMaterial color={HOLO_WARM} transparent opacity={open ? 0.4 : 0.15} /></mesh></group>; }

function Particles() { const ref = useRef<THREE.Points>(null); const positions = useMemo(() => { const arr = new Float32Array(700 * 3); for (let i = 0; i < 700; i++) { arr[i * 3] = (Math.random() - 0.5) * 14; arr[i * 3 + 1] = Math.random() * 8 - 1.5; arr[i * 3 + 2] = (Math.random() - 0.5) * 14; } return arr; }, []); useFrame((_, raw) => { if (ref.current) ref.current.rotation.y += Math.min(raw, 0.05) * 0.03; }); return <points ref={ref}><bufferGeometry><bufferAttribute attach="attributes-position" args={[positions, 3]} /></bufferGeometry><pointsMaterial size={0.028} color={HOLO} transparent opacity={0.55} sizeAttenuation /></points>; }
function Grid() { return <group position={[0, -1.35, 0]}><gridHelper args={[26, 26, HOLO, "#123b3a"]} /><mesh rotation-x={-Math.PI / 2}><circleGeometry args={[3.4, 64]} /><meshBasicMaterial color={HOLO} transparent opacity={0.06} /></mesh></group>; }

function ShieldDome({ open }: { open: boolean }) { const shell = useRef<THREE.Mesh>(null); const wire = useRef<THREE.Mesh>(null); const burst = useRef<THREE.Mesh>(null); const t = useRef(0); const burstT = useRef(0); const wasOpen = useRef(open); useFrame((state, raw) => { const dt = Math.min(raw, 0.05); if (open !== wasOpen.current) { wasOpen.current = open; if (open) burstT.current = 0.001; } const target = open ? 1 : 0; t.current += (target - t.current) * (1 - Math.exp(-7 * dt)); const pop = open ? 1 + Math.sin(t.current * Math.PI) * 0.12 : 1; const s = Math.max(0.001, t.current * 1.45 * pop); if (shell.current) { shell.current.scale.setScalar(s); (shell.current.material as THREE.MeshBasicMaterial).opacity = t.current * 0.16; } if (wire.current) { wire.current.scale.setScalar(s * 1.01); wire.current.rotation.y += dt * 0.25; wire.current.rotation.x = Math.sin(state.clock.elapsedTime * 0.4) * 0.08; (wire.current.material as THREE.MeshBasicMaterial).opacity = t.current * 0.32; } if (burst.current) { if (burstT.current > 0) { burstT.current += dt * 1.6; const p = Math.min(1, burstT.current); burst.current.visible = true; burst.current.scale.setScalar(0.4 + p * 2.6); (burst.current.material as THREE.MeshBasicMaterial).opacity = (1 - p) * 0.55; if (p >= 1) burstT.current = 0; } else burst.current.visible = false; } }); return <group position={[0, 0.55, 0]}><mesh ref={shell}><sphereGeometry args={[1, 48, 48]} /><meshBasicMaterial color={HOLO} transparent opacity={0} side={THREE.DoubleSide} depthWrite={false} /></mesh><mesh ref={wire}><icosahedronGeometry args={[1, 2]} /><meshBasicMaterial color={HOLO} wireframe transparent opacity={0} depthWrite={false} /></mesh><mesh ref={burst} visible={false}><sphereGeometry args={[1, 32, 32]} /><meshBasicMaterial color={HOLO_WARM} transparent opacity={0} wireframe depthWrite={false} /></mesh></group>; }

export function IdentityScene() { const [open, setOpen] = useState(false); return <div className="identity-scene"><Canvas camera={{ position: [0, 2.2, 7.4], fov: 45 }} dpr={[1, 2]}><color attach="background" args={["#eef1e9"]} /><fog attach="fog" args={["#eef1e9", 9, 22]} /><ambientLight intensity={0.62} /><directionalLight position={[4, 8, 5]} intensity={1.05} color={"#fff7e8"} /><Suspense fallback={null}><Environment><Lightformer intensity={1.1} position={[0, 5, 2]} scale={[8, 8, 1]} color={"#d7eee4"} /><Lightformer intensity={0.7} color={"#f1d2b4"} position={[-5, 1, -2]} rotation-y={Math.PI / 2} scale={[14, 2, 1]} /></Environment><group onClick={() => setOpen(v => !v)} position={[0, -0.35, 0]}><Robot screenColor={HOLO} shield /></group><ShieldDome open={open} /><ContactShadows position={[0, -1.34, 0]} opacity={0.55} scale={9} blur={2.4} far={4} color="#000000" /><AttributeField open={open} /><ChainRings open={open} /><Particles /><Grid /></Suspense></Canvas><p className="scene-hint">{open ? "shield active · identity field unsealed" : "tap Samvid to raise its shield"}</p><button className="scene-toggle" onClick={() => setOpen(v => !v)}>{open ? "seal shield" : "raise shield"}</button></div>; }
export default IdentityScene;
